<a href="https://colab.research.google.com/github/mdrifatmahmud/IT19040-Django-/blob/main/31_10_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
!wget -O Calculator.py https://github.com/rahmanziaur/EDGEICT/raw/main/Calculator.py # Download and save the file in current directory
import Calculator # Import by filename only

--2024-10-31 09:05:12--  https://github.com/rahmanziaur/EDGEICT/raw/main/Calculator.py
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/rahmanziaur/EDGEICT/main/Calculator.py [following]
--2024-10-31 09:05:12--  https://raw.githubusercontent.com/rahmanziaur/EDGEICT/main/Calculator.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 167 [text/plain]
Saving to: ‘Calculator.py’

Calculator.py       100%[===================>]     167  --.-KB/s    in 0s      

2024-10-31 09:05:12 (2.76 MB/s) - ‘Calculator.py’ saved [167/167]



array

In [14]:
import numpy as np
test = np.array ( [1,2,3])
q=15
for i in test:
  print (str(i) +"\n")
  print(q)

1

15
2

15
3

15


In [18]:
#test a type
type (test)
test.shape
test.ndim
test.dtype

dtype('int64')

In [19]:
test1=np.array ([[1,2,3],[4,5,6]])
test1

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
test2= np.array ([[1,2,3],[4,5,6],[4,5,6]], dtype=object)
print(test2)

[[1 2 3]
 [4 5 6]
 [4 5 6]]


In [29]:
#3d array print

array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])
for layer in array_3d:
    print(layer)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [30]:
for i, matrix in enumerate(array_3d):
    print(f"Matrix {i}:")
    for row in matrix:
        print(row)
    print()

Matrix 0:
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]

Matrix 1:
[13 14 15 16]
[17 18 19 20]
[21 22 23 24]



In [33]:
array_3d.shape
array_3d.ndim


3